import { TECH_TYPE } from './consts';

export const techCards = [
  { imageSrc: 'html-5.svg', text: 'HTML', type: TECH_TYPE.LANGUAGES },
  { imageSrc: 'css-3.svg', text: 'CSS', type: TECH_TYPE.LANGUAGES },
  { imageSrc: 'javascript.svg', text: 'Javascript', type: TECH_TYPE.LANGUAGES },
  { imageSrc: 'java.svg', text: 'Java', type: TECH_TYPE.LANGUAGES },
  { imageSrc: 'python.svg', text: 'Python', type: TECH_TYPE.LANGUAGES },
  { imageSrc: 'sql.svg', text: 'SQL', type: TECH_TYPE.LANGUAGES },
  { imageSrc: 'c.svg', text: 'C Language', type: TECH_TYPE.LANGUAGES },
  { imageSrc: 'react.svg', text: 'React.js', type: TECH_TYPE.FRONTEND },
  { imageSrc: 'redux.svg', text: 'Redux', type: TECH_TYPE.FRONTEND },
  { imageSrc: 'scss.svg', text: 'SCSS', type: TECH_TYPE.FRONTEND },
  { imageSrc: 'css-in-js.png', text: 'CSS in JS', type: TECH_TYPE.FRONTEND },
  { imageSrc: 'next-js.svg', text: 'Next.js', type: TECH_TYPE.FRONTEND },
  { imageSrc: 'spring.svg', text: 'Spring Boot', type: TECH_TYPE.BACKEND },
  { imageSrc: 'nodejs.svg', text: 'Node.js', type: TECH_TYPE.BACKEND },
  { imageSrc: 'express.png', text: 'Express', type: TECH_TYPE.BACKEND },
  { imageSrc: 'docker.svg', text: 'Docker', type: TECH_TYPE.BACKEND },
  { imageSrc: 'mysql.svg', text: 'MySQL', type: TECH_TYPE.DATABASE },
  { imageSrc: 'mongodb.png', text: 'Mongo DB', type: TECH_TYPE.DATABASE },
  { imageSrc: 'vertica.svg', text: 'Vertica', type: TECH_TYPE.DATABASE },
  { imageSrc: 'firebase.svg', text: 'FireStore', type: TECH_TYPE.DATABASE },
  { imageSrc: 'selenium.svg', text: 'Selenium', type: TECH_TYPE.TESTING },
  { imageSrc: 'junit.png', text: 'Junit', type: TECH_TYPE.TESTING },
  { imageSrc: 'jest.svg', text: 'Jest', type: TECH_TYPE.TESTING },
  { imageSrc: 'rest-assured.png', text: 'Rest Assured', type: TECH_TYPE.TESTING },
  { imageSrc: 'puppeteer.svg', text: 'Puppeteer', type: TECH_TYPE.TESTING },
  { imageSrc: 'git.svg', text: 'Git', type: TECH_TYPE.TOOLS },
  { imageSrc: 'jenkins.webp', text: 'Jenkins', type: TECH_TYPE.TOOLS },
  { imageSrc: 'jira.svg', text: 'Jira', type: TECH_TYPE.TOOLS },
  { imageSrc: 'npm.svg', text: 'NPM', type: TECH_TYPE.TOOLS },
  { imageSrc: 'eslint.svg', text: 'ESlint', type: TECH_TYPE.TOOLS },
];

export const animatedCards = [
  { title: 'Clean Code', text: "We spend most of our time reading code, let's make it readable and enjoyable.", imgSrc: 'clean-code.svg' },
  { title: 'Performance', text: 'Studies have shown the negative impact poor performance can have on business goals.', imgSrc: 'performance.svg' },
  { title: 'Testing', text: 'Less bugs leads to maintainable && flexible system which delivers a high quality product.', imgSrc: 'testing.svg' },
];

export const projects = [
  {
    title: 'FlixTime',
    subTitle: 'All your Favorite movies and TV Shows with a beautiful design',
    previewImage: '/projects/flixtime/flixtime2.webp',
    about: 'The main focus of this project was to sharpen my UI skills and build product with beautiful design from scratch',
    sliderImages: [
      { imgSrc: '/projects/flixtime/flixtime1.webp', imgAlt: 'screenshot1' },
      { imgSrc: '/projects/flixtime/flixtime2.webp', imgAlt: 'screenshot2' },
      { imgSrc: '/projects/flixtime/flixtime4.webp', imgAlt: 'screenshot4' },
      { imgSrc: '/projects/flixtime/flixtime3.webp', imgAlt: 'screenshot3' },
    ],
    keyFeatures: [
      'Design UI without any component system, only pure CSS (Styled Components).',
      '100% Responsive, using Media queries, Grid & Flexbox layouts.',
      'Server side rendered app, with serverless functions to fetch the data.',
      'Using TMDB API as the data source, parallel fetching with axios.',
      'Functionality: Searching, Filtering and Sorting.',
    ],
    techUsedIcons: [
      { iconSrc: '/devIcons/next-js.svg', iconTitle: 'Next.js' },
      { iconSrc: '/devIcons/react.svg', iconTitle: 'React' },
      { iconSrc: '/devIcons/css-in-js.png', iconTitle: 'CSS-in-JS' },
    ],
    sourceCodeLink: 'https://github.com/Icohen007',
    liveDemoLink: 'https://flixtime.now.sh',
  },
  {
    title: 'NextyShop',
    subTitle: 'The best shop in the city',
    previewImage: '/projects/nexty/nexty1.jpg',
    about: 'in this project I built eCommerce Shop - with the MERN Stack(MongoDB, Express, React, Node.js), my first fullstack application.',
    sliderImages: [
      { imgSrc: '/projects/nexty/nexty1.jpg', imgAlt: 'screenshot1' },
      { imgSrc: '/projects/nexty/nexty2.jpg', imgAlt: 'screenshot2' },
      { imgSrc: '/projects/nexty/nexty3.jpg', imgAlt: 'screenshot3' },
      { imgSrc: '/projects/nexty/nexty4.jpg', imgAlt: 'screenshot4' },
      { imgSrc: '/projects/nexty/nexty5.jpg', imgAlt: 'screenshot5' },
      { imgSrc: '/projects/nexty/nexty6.jpg', imgAlt: 'screenshot6' },
    ],
    keyFeatures: [
      'Creating an entire Express API from scratch',
      'User authentication with JWT and cookies',
      'Password hashing with bcrypt',
      'Authorization, Roles, and Protected Routes',
      'Dynamically uploading images with Cloudinary API',
      'Modelling database content with Mongoose schemas',
      'Pagination with MongoDB',
      'Payment of Stripe API',
      'Form and requests Validation in server side',
    ],
    techUsedIcons: [
      { iconSrc: '/devIcons/next-js.svg', iconTitle: 'Next.js' },
      { iconSrc: '/devIcons/react.svg', iconTitle: 'React' },
      { iconSrc: '/devIcons/css-in-js.png', iconTitle: 'CSS-in-JS' },
      { iconSrc: '/devIcons/mongodb.png', iconTitle: 'MongoDB' },
      { iconSrc: '/devIcons/express.png', iconTitle: 'Express' },
      { iconSrc: '/devIcons/jwt.svg', iconTitle: 'JWT' },
      { iconSrc: '/devIcons/stripe.svg', iconTitle: 'Stripe' },
    ],
    sourceCodeLink: 'https://github.com/Icohen007',
    liveDemoLink: 'https://nextyshop.herokuapp.com',
  },
  {
    title: 'FlixTime',
    subTitle: 'All your Favorite movies and TV Shows with a beautiful design',
    previewImage: '/projects/flixtime/flixtime2.webp',
    about: 'The main focus of this project was to sharpen my UI skills and build product with beautiful design from scratch',
    sliderImages: [
      { imgSrc: '/projects/flixtime/flixtime1.webp', imgAlt: 'screenshot1' },
      { imgSrc: '/projects/flixtime/flixtime2.webp', imgAlt: 'screenshot2' },
      { imgSrc: '/projects/flixtime/flixtime4.webp', imgAlt: 'screenshot4' },
      { imgSrc: '/projects/flixtime/flixtime3.webp', imgAlt: 'screenshot3' },
    ],
    keyFeatures: [
      'Design UI only with pure CSS (Styled Components), no component system',
      'Server side rendered app, with serverless functions to fetch the data',
      'Using TMDB API as the data source',
      'Functionality from API into Client: Searching, Filtering and Sorting',
    ],
    techUsedIcons: [
      { iconSrc: '/devIcons/next-js.svg', iconTitle: 'Next.js' },
      { iconSrc: '/devIcons/react.svg', iconTitle: 'React' },
      { iconSrc: '/devIcons/css-in-js.png', iconTitle: 'CSS-in-JS' },
    ],
    sourceCodeLink: 'https://github.com/Icohen007',
    liveDemoLink: 'https://flixtime.now.sh',
  },
  {
    title: 'FlixTime',
    subTitle: 'All your Favorite movies and TV Shows with a beautiful design',
    previewImage: '/projects/flixtime/flixtime2.webp',
    about: 'The main focus of this project was to sharpen my UI skills and build product with beautiful design from scratch',
    sliderImages: [
      { imgSrc: '/projects/flixtime/flixtime1.webp', imgAlt: 'screenshot1' },
      { imgSrc: '/projects/flixtime/flixtime2.webp', imgAlt: 'screenshot2' },
      { imgSrc: '/projects/flixtime/flixtime4.webp', imgAlt: 'screenshot4' },
      { imgSrc: '/projects/flixtime/flixtime3.webp', imgAlt: 'screenshot3' },
    ],
    keyFeatures: [
      'Design UI only with pure CSS (Styled Components), no component system',
      'Server side rendered app, with serverless functions to fetch the data',
      'Using TMDB API as the data source',
      'Functionality from API into Client: Searching, Filtering and Sorting',
    ],
    techUsedIcons: [
      { iconSrc: '/devIcons/next-js.svg', iconTitle: 'Next.js' },
      { iconSrc: '/devIcons/react.svg', iconTitle: 'React' },
      { iconSrc: '/devIcons/css-in-js.png', iconTitle: 'CSS-in-JS' },
    ],
    sourceCodeLink: 'https://github.com/Icohen007',
    liveDemoLink: 'https://flixtime.now.sh',
  },
];
